DROP PROCEDURE IF EXISTS Fecha3;

DELIMITER $$
CREATE PROCEDURE Fecha3(IN f DATE)
BEGIN
	IF (DAY(f)<10 AND MONTH(f)<10) THEN
		SELECT CONCAT("0",DAY(f),"/","0",MONTH(f),"/",YEAR(f))AS fecha;
	ELSE 
		SELECT CONCAT(DAY(f),"/",MONTH(f),"/",YEAR(f))AS fecha;
	END IF;
	
	
END $$

DELIMITER ;