DROP PROCEDURE IF EXISTS mes;

DELIMITER $$

CREATE PROCEDURE mes(IN m INT)
BEGIN
	CASE m
		WHEN 1 THEN SELECT 'Enero' AS MES;
		WHEN 2 THEN SELECT 'Febrero' AS MES;
		WHEN 3 THEN SELECT 'Marzo' AS MES;
		WHEN 4 THEN SELECT 'Abril' AS MES;
		WHEN 5 THEN SELECT 'Mayo' AS MES;
		WHEN 6 THEN SELECT 'Junio' AS MES;
		WHEN 7 THEN SELECT 'Julio' AS MES;
		WHEN 8 THEN SELECT 'Agosto' AS MES;
		WHEN 9 THEN SELECT 'Septiembre' AS MES;
		WHEN 10 THEN SELECT 'Octubre' AS MES;
		WHEN 11 THEN SELECT 'Noviembre' AS MES;
		WHEN 12 THEN SELECT 'Diciembre' AS MES;
		ELSE SELECT 'No es un mes valido' AS MES;
	END CASE;
END $$

DELIMITER ;