DROP FUNCTION ValidarFecha;
DELIMITER $$
CREATE FUNCTION ValidarFecha(d INT, m INT, y INT) RETURNS BOOLEAN
BEGIN
	DECLARE nd INT;
	SET nd=31;
	
	IF(y=0)THEN
		RETURN FALSE;
	END IF;
	
	IF(m>12 OR m<1)THEN
		RETURN FALSE;
	ELSEIF(m=4 OR m=6 OR m=9 OR m=11)THEN
		SET nd=30;
	ELSEIF(m=2)THEN
		SET nd=28;
	END IF;
	
	IF(d<0 OR d>nd)THEN
		RETURN FALSE;
	END IF;
	RETURN TRUE;
END $$
DELIMITER ;